on: [push]

jobs:
  user_api:
    runs-on: ubuntu-latest
    name: User test API
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: inactive user action
        id: inactive-user
        uses: meiyanathanj/inactive-user-sample@v1.3
        with:
          token: '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'
          orgs-name: 'internal-test-organization'
      # Use the output from the `inactive-user` step
      - name: Get the output
        run: echo "The time was ${{ steps.inactive-user.outputs.status }}"
