on: [push]

jobs:
  user_api:
    runs-on: ubuntu-latest
    name: User test API
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: inactive user action
        id: inactive-user
        uses: meiyanathanj/inactive-user-sample@v1.2
        with:
          token: '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'
          orgs-name: 'internal-test-organization'
      # Use the output from the `inactive-user` step
      - name: Get the output
        run: echo "The time was ${{ steps.inactive-user.outputs.status }}"
